In [1]:
from numpy import *

In [6]:
a = array([[1, 2], [0, 2]])
b = array([[1, 3], [1, 0]])


In [7]:
a+b

array([[2, 5],
       [1, 2]])

In [9]:
a.ndim

2

In [11]:
c = array([i for i in range(16)])
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [21]:
d=c.reshape((2,2,2,2))
d

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [20]:
d[0,0,0,0]

0

In [26]:
a = array([[0,1,0,1,0,0],
           [1,0,0,1,0,0],
           [0,0,0,1,1,0],
           [1,1,1,0,1,1],
           [0,0,1,1,0,0],
           [0,0,0,1,0,0]])
sum(a ** 4)


14

In [27]:
from ATP import *

In [45]:
def BFS(a, v):
    red = Queue()
    izlaz = list()
    
    red.enqueue(v)
    izlaz.append(v)
    
    while not red.isEmpty():
        v = red.dequeue()
        for i in range(len(a)):
            if a[v][i] == 1:
                if i not in izlaz:
                    red.enqueue(i)
                    izlaz.append(i)
    return izlaz

In [49]:
t = array([[0,1,0,1],
           [1,0,1,1],
           [0,1,0,1],
           [1,1,1,0]])

BFS(t,0)

[0, 1, 3, 2]

In [40]:
## BFS
def skakac(xp, yp, xk, yk):
    a = [[-1] * 8 for i in range(8)]
    red = Queue()
    a[xp][yp] = 0
    red.enqueue((xp, yp))
    dr = [(-2,-1), (-2,1), (-1,-2), (-1,2), (2,-1), (2,1), (1,-2), (1,2)]
    while a[xk][yk] == -1:
        x, y = red.dequeue()
        for dx, dy in dr:
            if x + dx >= 0 and x + dx < 8 and y + dy >= 0 and y + dy < 8:
                if a[x + dx][y + dy] == -1:
                    a[x + dx][y + dy] = a[x][y] + 1
                    red.enqueue((x + dx, y + dy))
    print(a)
    return a[xk][yk]
            


In [41]:
print(skakac(3,3,5,5))

[[2, 3, 2, 3, 2, 3, 2, 3], [3, 4, 1, 2, 1, 4, 3, 2], [2, 1, 2, 3, 2, 1, 2, 3], [3, 2, 3, 0, 3, 2, 3, 2], [2, 1, 2, 3, 2, 1, 2, 3], [3, 4, 1, 2, 1, 4, 3, 2], [2, 3, 2, 3, 2, 3, 2, 3], [3, 2, 3, 2, 3, 2, 3, -1]]
4


In [50]:
## DFS
def DFS(a, v):
    stog = Stack()
    stog.push(v)
    izlaz = list()
    while not stog.isEmpty():
        v = stog.pop()
        if v not in izlaz:
            izlaz.append(v)
        for i in range(len(a)-1, -1, -1):
            if a[v][i] == 1:
                if i not in izlaz:
                    stog.push(i)
    return izlaz

In [51]:
t = array([[0,1,0,1],
           [1,0,1,1],
           [0,1,0,1],
           [1,1,1,0]])

DFS(t,0)

[0, 1, 2, 3]